import {
  Users,
  FileBarChart,
  BarChart3,
  Calendar,
  DollarSign,
  Settings,
  Settings2,
  Mail,
  Wrench,
  Scale,
  Briefcase,
  Play,
  Trophy,
  ArrowLeftRight,
  Target,
  PartyPopper,
} from 'lucide-react';
import React from 'react';

export const iconMap: Record<string, React.ElementType> = {
  Associados: Users,
  Associado: Users,
  'Catraca Control ID': Settings,
  'Catraca Topdata': Settings,
  'Ocorrências e Agenda': Calendar,
  'Ocorrências E agenda': Calendar,
  Financeiro: DollarSign,
  Orçamento: BarChart3,
  Contábil: FileBarChart,
  Materiais: Wrench,
  'Mala Direta': Mail,
  'Entrada/Saída': ArrowLeftRight,
  Esportes: Trophy,
  Eventos: PartyPopper,
  Jurídico: Scale,
  Administrativo: Briefcase,
  Parâmetros: Settings2,
  Documentos: FileBarChart,
  Relatórios: BarChart3,
  default: Target,
};
