CREATE DATABASE IF NOT EXISTS conhe_siclus;

USE conhe_siclus;

ck
CREATE TABLE IF NOT EXISTS categorias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    icone VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS submenus (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    conteudo TEXT NOT NULL,
    grupo VARCHAR(255),
    categoriaId INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (categoriaId) REFERENCES categorias (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS submenu_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    submenuId INT NOT NULL,
    url VARCHAR(255) NOT NULL,
    FOREIGN KEY (submenuId) REFERENCES submenus (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS submenu_videos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    submenuId INT NOT NULL,
    url VARCHAR(255) NOT NULL,
    FOREIGN KEY (submenuId) REFERENCES submenus (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS submenu_related (
    submenuId INT NOT NULL,
    relatedSubmenuId INT NOT NULL,
    PRIMARY KEY (submenuId, relatedSubmenuId),
    FOREIGN KEY (submenuId) REFERENCES submenus (id) ON DELETE CASCADE,
    FOREIGN KEY (relatedSubmenuId) REFERENCES submenus (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);